export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const INCREASE_PRODUCT_QUANTITY = 'INCREASE_PRODUCT_QUANTITY';
export const DECREASE_PRODUCT_QUANTITY = 'DECREASE_PRODUCT_QUANTITY';
export const CHANGE_MANUALLY_PRODUCT_QUANTITY = 'CHANGE_MANUALLY_PRODUCT_QUANTITY';
export const SET_CART = 'SET_CART';


